version: '3.8'

services:
  # 1. MySQL Database Container (System of Record)
  mysql_db:
    image: mysql:8.0
    container_name: airline-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: John@123
      MYSQL_DATABASE: airline_db
      MYSQL_USER: root
      MYSQL_PASSWORD: John@123
    ports:
      # **** CRITICAL CHANGE: Using port 3308 on the host machine ****
      - "3308:3306"
    volumes:
      # Persist the data outside the container
      - db_data:/var/lib/mysql

volumes:
  db_data:
