version: '3.8'
services:
  mysql_db:
    image: mysql:8.0
    container_name: airline-mysql-db
    environment:
      # CRITICAL: This password must match the one in your DbUtils.java
      MYSQL_ROOT_PASSWORD: John@123
      MYSQL_DATABASE: airline_db
    # Maps the container's internal port 3306 to the host's port 3308
    # The 'host.docker.internal' address will correctly map back to the host machine's network
    # where the container is running.
    ports:
      - "3308:3306"
    volumes:
      # Optional: Mount your SQL initialization script here if needed
      # - ./init-db:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql

volumes:
  db_data: