pipeline {
    agent any

    tools {
        // Assumes a JDK named 'jdk11' is configured in Jenkins Global Tool Configuration
        jdk 'jdk11'
        maven 'maven3' // Assumes Maven is configured in Jenkins Global Tool Configuration
    }

    stages {
        stage('Build') {
            steps {
                echo 'Building the project...'
                // The 'bat' step is for Windows. Use 'sh' for Linux/macOS.
                bat 'mvn compile'
            }
        }
        stage('Test') {
            steps {
                echo 'Running tests...'
                bat 'mvn test'
            }
        }
    }

    post {
        always {
            echo 'Archiving test results...'
            // Archive the TestNG reports generated by Maven Surefire
            archiveArtifacts artifacts: 'target/surefire-reports/emailable-report.html', allowEmptyArchive: true
        }
    }
}